version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: cinephoria_database
    restart: always
    environment:
      # 🚀 On pioche dans le fichier d'environnement chargé
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      # 🚀 Le port externe devient dynamique (3307 en dev, 3306 en prod)
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: